### ISSUE TITLE
style_transfer.py runs with no output

### ISSUE THREAD

**Issue by Catalyzzt** [crowsonkb/style-transfer-pytorch#2]
style_transfer.py is running with no output and no error messages. I'm pretty sure it's set up incorrectly. Below are screenshots of my folders:
![image](https://user-images.githubusercontent.com/78272915/106363736-64f32580-62f8-11eb-83b4-1b5f4f9ec876.png)
![image](https://user-images.githubusercontent.com/78272915/106363748-72101480-62f8-11eb-94d5-866a26801525.png)
main_images, output_images, and style_images are user-created folders. Running the command does nothing:
![image](https://user-images.githubusercontent.com/78272915/106363780-9bc93b80-62f8-11eb-8ba4-4dc89d69e0a5.png)
(this is python style_transfer.py [main] [style])
I have tried using the --web interface with localhost:8080 but nothing appears.

**Comment by crowsonkb** [comment]
Try running:

```
pip install -e F:\style-transfer-pytorch-master
```

and then running `style_transfer` instead of `python style_transfer.py`. `style_transfer.py` does not have a main method and this will not do anything.

Hope this helps :)

**Comment by Catalyzzt** [comment]
Thanks so much for the response! Worked like a charm!
